### ISSUE TITLE
Add to Stackage?

### ISSUE THREAD

**Issue by ocramz** [viercc/trie-simple#1]

**Comment by viercc** [comment]
Sorry for ignoring this issue for years. I've not known the workflow of adding a package to Stackage at the time, thought "I'll learn later," then forgot. Sorry again!

I finally read the [how-to](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package) and am willing to add it to Stackage, but I can't do it right now. It'll be around Friday.

**Comment by viercc** [comment]
Wait, there already is? I think it's already done anyway.

https://www.stackage.org/nightly-2023-04-05/package/trie-simple-0.4.1.1
