### ISSUE TITLE
Gauge is deprecated and doesn't build with GHC 9.10

### ISSUE THREAD

**Issue by TeofilC** [viercc/trie-simple#15]
The gauge package is used by the benchmark suite. It has been deprecated and doesn't compile with GHC 9.10.

I would be happy to prepare a PR that migrates this package to [criterion](https://hackage.haskell.org/package/criterion) or [tasty-bench](https://hackage.haskell.org/package/tasty-bench)

See also: https://github.com/commercialhaskell/stackage/issues/7609

**Comment by viercc** [comment]
Thank you! I'd welcome a PR. I'd like to migrate this benchmark to `tasty-bench` if there's no trouble.
